wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    code_path: code/ROAR_Gym/e2eModel.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    start_time: 1656468200
    t:
      1:
      - 1
      - 41
      2:
      - 1
      - 41
      3:
      - 5
      - 13
      - 14
      - 16
      - 22
      - 34
      4: 3.7.9
      5: 0.12.11
      8:
      - 3
      - 5
env_name:
  desc: null
  value: roar-e2e-ppo-v0
policy_type:
  desc: null
  value: CnnPolicy
training_kwargs:
  desc: null
  value:
    batch_size: 64
    device: cpu
    ent_coef: 0.0
    gamma: 0.99
    learning_rate: 1.0e-05
    n_steps: 8192
    seed: 1
    verbose: 1
